sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install
  - travis_wait

script:
  - npm test
  - npm start
  - npm build

notifications:
  email:
    - kelvin.mijaya@taralite.com